// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Zi1YqBaIBOZkgsLdZDnXSvSZrRSdQm8',
    appId: '1:203324410746:web:1ffb0371f035dba7dbe4c3',
    messagingSenderId: '203324410746',
    projectId: 'cryptrend-176d3',
    authDomain: 'cryptrend-176d3.firebaseapp.com',
    storageBucket: 'cryptrend-176d3.firebasestorage.app',
    measurementId: 'G-P6E8FRGVME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOFpzp_OJcIlpw_xpUDMQdnSx2UtuHD4Y',
    appId: '1:203324410746:android:1c2d952e24e2c754dbe4c3',
    messagingSenderId: '203324410746',
    projectId: 'cryptrend-176d3',
    storageBucket: 'cryptrend-176d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXosC2lLO1qaj514lkvvxu6HSTbQ5IOqA',
    appId: '1:203324410746:ios:adb5e051135c6193dbe4c3',
    messagingSenderId: '203324410746',
    projectId: 'cryptrend-176d3',
    storageBucket: 'cryptrend-176d3.firebasestorage.app',
    iosBundleId: 'com.example.crypttrend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXosC2lLO1qaj514lkvvxu6HSTbQ5IOqA',
    appId: '1:203324410746:ios:adb5e051135c6193dbe4c3',
    messagingSenderId: '203324410746',
    projectId: 'cryptrend-176d3',
    storageBucket: 'cryptrend-176d3.firebasestorage.app',
    iosBundleId: 'com.example.crypttrend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4Zi1YqBaIBOZkgsLdZDnXSvSZrRSdQm8',
    appId: '1:203324410746:web:6684ac34c9b856afdbe4c3',
    messagingSenderId: '203324410746',
    projectId: 'cryptrend-176d3',
    authDomain: 'cryptrend-176d3.firebaseapp.com',
    storageBucket: 'cryptrend-176d3.firebasestorage.app',
    measurementId: 'G-ETJ7G5EYRV',
  );
}
